# Static Inventory - Development Environment
# Used as fallback when AWS dynamic inventory is unavailable
# or for local testing with Vagrant/Docker
---
all:
  children:
    webservers:
      hosts:
        web-dev-01:
          ansible_host: 10.0.1.10
          ansible_user: ec2-user
          ec2_instance_type: t3.micro
          ec2_availability_zone: us-east-1a

    dbservers:
      hosts:
        db-dev-01:
          ansible_host: 10.0.2.10
          ansible_user: ec2-user
          ec2_instance_type: t3.small
          ec2_availability_zone: us-east-1a
          postgresql_version: "15"

    appservers:
      hosts:
        app-dev-01:
          ansible_host: 10.0.3.10
          ansible_user: ec2-user
          ec2_instance_type: t3.micro
          ec2_availability_zone: us-east-1a

    # Local testing with Vagrant
    vagrant:
      hosts:
        vagrant-web:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/web/virtualbox/private_key
        vagrant-db:
          ansible_host: 192.168.56.11
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/db/virtualbox/private_key

    # Docker testing
    docker:
      hosts:
        docker-web:
          ansible_host: 172.17.0.2
          ansible_connection: docker
          ansible_docker_extra_args: "-H unix:///var/run/docker.sock"
        docker-db:
          ansible_host: 172.17.0.3
          ansible_connection: docker
          ansible_docker_extra_args: "-H unix:///var/run/docker.sock"

  vars:
    # Global variables for all hosts
    ansible_python_interpreter: /usr/bin/python3
    environment_name: dev
    project_name: chikwex-infra
